find_program(CCACHE_EXECUTABLE ccache)
if(CCACHE_EXECUTABLE)
  if(DEFINED CCACHE_SLOPPINESS)
    set(ccache_sloppiness "${CCACHE_SLOPPINESS}")
  elseif(DEFINED ENV{CCACHE_SLOPPINESS})
    set(ccache_sloppiness "$ENV{CCACHE_SLOPPINESS}")
  else()
    set(ccache_sloppiness "pch_defines,time_macros")
  endif()
  foreach(lang IN ITEMS C CXX OBJC OBJCXX CUDA)
    set(CMAKE_${lang}_COMPILER_LAUNCHER
      "${CMAKE_COMMAND}" -E env CCACHE_SLOPPINESS="${ccache_sloppiness}" "${CCACHE_EXECUTABLE}" PARENT_SCOPE)
  endforeach()
endif()
