find_program(Ccache_EXECUTABLE ccache)
if(Ccache_EXECUTABLE)
  foreach(lang IN ITEMS C CXX OBJC OBJCXX CUDA)
    set(CMAKE_${lang}_COMPILER_LAUNCHER "${Ccache_EXECUTABLE}" PARENT_SCOPE)
  endforeach()
endif()
